CREATE DATABASE appdb;
GO

USE appdb;
GO

CREATE TABLE users (
    id BIGINT IDENTITY PRIMARY KEY,
    username NVARCHAR(100) NOT NULL UNIQUE,
    email NVARCHAR(255) NOT NULL,
    created_at DATETIME2 DEFAULT SYSDATETIME()
);
